export const stages = [
  { id: '43819', name: 'Novo', role: 'Entrada (site, formulário Meta/RD, importação)' },
  { id: '66328', name: 'IA atendendo', role: 'Bot conversando com o lead' },
  { id: '66329', name: 'Qualificado pela IA', role: 'Fila de trabalho do time' },
  { id: '43820', name: 'Contato', role: 'Vendedor puxou o lead para si' },
  { id: '43821', name: 'Qualificação', role: '—' },
  { id: '43822', name: 'Negociação', role: '—' },
  { id: '43823', name: 'Fechamento', role: '—' },
  { id: '49522', name: 'Fechado (ganho)', role: '—' },
  { id: '45972', name: 'Declinado (perdido)', role: 'Descarte (opt-out / número errado)' },
]

export const automations = [
  {
    id: 'captacao',
    num: '1',
    name: 'Captação bragança',
    short: 'Recebe o lead da RD Station / LP e coloca na coluna "Novo" do funil.',
    workflowId: 'cYkdLhOi8Y7lzUR1',
    trigger: 'Webhook POST /webhook/rd-station',
    flow: [
      { label: 'Webhook RD', desc: 'Porta de entrada que recebe o POST disparado pela automação da RD Station a cada conversão de landing page.' },
      { label: 'E1 Normalizar lead', desc: 'Limpa e valida os dados: telefone (DDD + 9), nome, vidas e tipo de plano. Mapeia a fonte e a marca da campanha e monta o payload de criação.' },
      { label: 'E2 Criar negociação', desc: 'Cria a negociação no funil 6777 na coluna "Novo" (43819), junto com o contato e os campos personalizados.' },
      { label: 'E3 Interpretar', desc: 'Lê a resposta do CRM. Se criou, guarda o id da negociação; se falhou, captura o motivo do erro.' },
      { label: 'E4 Registrar no Supabase', desc: 'Insere a linha em chat_sessions (trigger_type=rdstation) com status nova ou erro_crm, para rastreio.' },
      { label: 'E5 Responder ao RD', desc: 'Devolve ao RD um resumo: quantos recebeu, criou e ignorou.' },
    ],
    notes: [
      'Não atribui vendedor — a roleta só gira depois da qualificação.',
      'Normaliza telefone (DDD + 9), mapeia fonte e marca da campanha.',
      'Grava o texto da faixa de vidas, não só o número mínimo.',
      'Responde ao RD: status, recebidos, criados e ignorados.',
    ],
  },
  {
    id: 'trilha-e',
    num: '2',
    name: 'Amil/GNDI — Trilha E',
    short: 'Orquestrador: aborda leads em "Novo", dispara a IA e cuida da transferência.',
    workflowId: '7Y7HKH5tl3cDx7i5',
    trigger: 'Cron 1 min + Cron 10 min + Webhook crm-transferir',
    flow: [
      { label: 'Cron 1min → aborda "Novo"', desc: 'A cada 1 minuto busca negociações em "Novo" e aplica travas anti-spam, anti-clone e LGPD (respeita opt-out).' },
      { label: 'C4 Monta contexto', desc: 'Reúne nome, cidade, plano e vidas do lead e prepara a mensagem de abertura que o agente vai processar.' },
      { label: 'C6 Inicia agente IA', desc: 'Chama o agente 17530 (Amil_Braganca_Bot) para iniciar o atendimento no WhatsApp do lead.' },
      { label: 'C8 Move para IA atendendo', desc: 'Move o card para 66328 (IA atendendo) após o disparo; se falhar, mantém em "Novo" para tentar de novo.' },
      { label: 'Cron 10min → transfere por silêncio', desc: 'A cada 10 minutos transfere quem não respondeu em 210 min (3h30), encaminhando para a fila do time.' },
    ],
    notes: [
      'Ramo C (1min): aborda leads em Novo com travas anti-spam/anti-clone e LGPD.',
      'Ramo D (10min): transfere por silêncio quem não respondeu em 210 min.',
      'Ramo B: transferência manual/por motivo (compartilha nós do fluxo 3.A).',
    ],
  },
  {
    id: 'transferir',
    num: '3',
    name: '3.A — Webhook: Transferir',
    short: 'Transfere o lead para consultor humano girando a mesma fila do site.',
    workflowId: 'ow35uJafwXcn4dA5',
    trigger: 'Webhook POST /webhook/crm-transferir',
    flow: [
      { label: 'Webhook', desc: 'Recebe a chamada do agente do CRM pedindo a transferência para um consultor humano.' },
      { label: 'B1 Validar', desc: 'Interpreta o motivo (qualificado, pediu_humano, tema_sensivel, opt_out etc.), limpa placeholders e normaliza telefone. Descobre de quem é a conversa via inbox se faltar o id.' },
      { label: 'B1b Localizar negociação', desc: 'Busca no CRM os cards que existem agora pelo telefone, para não usar um id antigo ("fantasma").' },
      { label: 'B2 Fila próximo vendedor', desc: 'Chama a RPC proximo_vendedor(p_unidade) no Supabase para girar a roleta da unidade e pegar o próximo consultor da fila.' },
      { label: 'B4 Montar transferência', desc: 'Define o estágio de destino (Qualificado IA ou Declinado), valida o card e monta o patch. Nunca rebaixa card já entregue.' },
      { label: 'B3 Atribuir/mover', desc: 'Atualiza no CRM: id_usuario do vendedor, estágio e próxima ação.' },
      { label: 'B5 Registrar Supabase', desc: 'Grava no chat_sessions o status qualificada/descartada, motivo e observações.' },
      { label: 'B6 Responder', desc: 'Informa ao agente para quem foi transferido e em qual número o consultor vai chamar.' },
      { label: 'B7 Encerrar sessão', desc: 'Encerra a sessão do agente para ele não responder por cima do consultor.' },
    ],
    notes: [
      'Motivos: qualificado, pediu_humano, tema_sensivel, opt_out, numero_errado, sem_resposta.',
      'opt_out e numero_errado vão para "Declinado" sem gastar a roleta.',
      'Nunca rebaixa card já entregue ao vendedor.',
      'Usa fallback por inbox e valida o id para evitar card "fantasma".',
    ],
  },
  {
    id: 'qualificado',
    num: '4',
    name: '3.B — Weebhook: qualificado',
    short: 'Grava a qualificação do agente, calcula o score e encadeia a transferência.',
    workflowId: 'ZkI81pag9YTt4YN2',
    trigger: 'Webhook POST /webhook/longlife-qualificacao',
    flow: [
      { label: 'Webhook', desc: 'Recebe a qualificação enviada pelo agente de IA ao encerrar a conversa (qualificado ou parcial).' },
      { label: 'A1 Validar', desc: 'Normaliza os dados (perfil, vidas, cidade, temperatura) e calcula o score (0–100) a partir do que a IA apurou.' },
      { label: 'A1b/A1c Resolver id', desc: 'Localiza o card correto no CRM pelo id ou telefone, corrigindo ids antigos.' },
      { label: 'A2 Gravar Supabase', desc: 'Atualiza chat_sessions com status, score, observações e os campos da qualificação.' },
      { label: 'A3 Atualizar CRM', desc: 'Atualiza a negociação no CRM com os dados da qualificação.' },
      { label: 'A4 Explodir campos', desc: 'Transforma em um item por campo personalizado e garante qualifica_IA = sim e a transcrição.' },
      { label: 'A5 Upsert campo', desc: 'Grava cada campo personalizado no CRM (tipo_plano, vidas, cidade, tem_plano_hoje, transcrição, qualifica_IA).' },
      { label: 'A5b-A5d Transferência', desc: 'Junta os itens e encadeia automaticamente a transferência do lead (motivo qualificado).' },
      { label: 'A6 Responder', desc: 'Devolve ao agente o resultado da gravação e da transferência.' },
    ],
    notes: [
      'Calcula o score (0–100) a partir dos dados apurados pela IA.',
      'Grava campos: tipo_plano, vidas, cidade, tem_plano_hoje, transcrição e qualifica_IA.',
      'qualifica_IA = sim é obrigatório para a trilha Qualifica IA.',
      'Encadeia automaticamente a transferência (uma ferramenta só).',
    ],
  },
  {
    id: 'qualifica-ia',
    num: '5',
    name: '4 — Qualifica_IA_Braganca',
    short: 'Move para "Qualificado pela IA" os leads já qualificados pelo bot.',
    workflowId: 'oaHzdvwg6RNlgsGg',
    trigger: 'Cron a cada 1 min',
    flow: [
      { label: 'Listar IA Atendendo', desc: 'A cada 1 minuto busca negociações do funil 6777 para analisar.' },
      { label: 'Preparar Lote', desc: 'Filtra apenas quem está em 66328 (IA atendendo) e seleciona até 35 negócios (20 recentes + 15 rotativos).' },
      { label: 'Filtrar qualifica_IA', desc: 'Lê o campo personalizado qualifica_IA (5587) e seleciona os que têm valor sim/true.' },
      { label: 'Tem qualificados?', desc: 'Se não houver qualificados, encerra; caso contrário, segue para mover.' },
      { label: 'Mover para 66329', desc: 'Move o card para "Qualificado pela IA" (66329) com a próxima ação aguardando consultor.' },
    ],
    notes: [
      'Verifica o campo qualifica_IA (5587) = sim.',
      'Processa até 35 negócios por execução (20 recentes + 15 rotativos).',
      'Garante que o lead qualificado não fica preso na conversa com o bot.',
    ],
  },
  {
    id: 'handoff-130min',
    num: '6',
    name: 'Handoff_IA_130min_Braganca',
    short: 'Encaminha leads parados há 130 min em "IA atendendo" para a fila do time.',
    workflowId: 'lvcexDiMlxf3ojNO',
    trigger: 'Cron a cada 5 min',
    flow: [
      { label: 'Listar Funil', desc: 'A cada 5 minutos busca as negociações do funil 6777.' },
      { label: 'Filtrar 130min IA', desc: 'Seleciona quem está há 130 min ou mais em IA atendendo, usando o tempo rastreado em memória (staticData).' },
      { label: 'Tem candidatos?', desc: 'Se houver candidatos, inicia o lote; senão, encerra a execução.' },
      { label: 'Fila próximo vendedor', desc: 'Gira a roleta (proximo_vendedor com a unidade Bragança) para pegar o consultor — a menos que o lead já tenha um vendedor humano.' },
      { label: 'Montar transferência', desc: 'Define estágio 66329, dono do vendedor e monta o patch para CRM e Supabase.' },
      { label: 'Atribuir/mover', desc: 'Atualiza o card no CRM: vendedor, estágio e próxima ação.' },
      { label: 'Registrar Supabase', desc: 'Grava no chat_sessions a transferência (etapa transferida_sem_resposta).' },
      { label: 'Encerrar sessão', desc: 'Encerra a sessão do agente para liberar a conversa ao consultor.' },
    ],
    notes: [
      'Rastreia o tempo via staticData (não UpdatedAt).',
      'Respeita vendedor humano já atribuído — não gira a fila de novo.',
      'Lote de até 15 por execução; pula itens sem vendedor disponível.',
    ],
  },
]

export const infra = [
  { resource: 'CRM (API Lumion)', value: 'integracao.agendasistemacrm.com.br/api/v1' },
  { resource: 'n8n', value: 'n8n.unificahub.com.br' },
  { resource: 'Supabase', value: 'jlyqptmxcloouaxumdqu.supabase.co' },
  { resource: 'Fila de vendedores', value: 'RPC proximo_vendedor(p_unidade) · tabela vendedores_fila' },
  { resource: 'Agente de IA', value: 'Bragança 17530 (Amil_Braganca_Bot) · Jundiaí 16306 (Agente SDR Jundiaí)' },
  { resource: 'Conexão WhatsApp', value: 'dinâmica (LON-23): Bragança 27059 · Jundiaí 26926' },
]

export const customFields = [
  { field: 'tipo_plano', id: '5280' },
  { field: 'vidas', id: '3313' },
  { field: 'cidade', id: '3319' },
  { field: 'tem_plano_hoje', id: '5281' },
  { field: 'transcrição / resumo', id: '5284' },
  { field: 'qualifica_IA', id: '5587' },
]

// ---------------------------------------------------------------------------
// Jundiaí (funil 7175) — mesmo modelo da Bragança, isolado por unidade.
// ---------------------------------------------------------------------------

export const stagesJundiai = [
  { id: '46938', name: 'Novo', role: 'Entrada RD / site' },
  { id: '73692', name: 'IA atendendo', role: 'Bot conversando' },
  { id: '73693', name: 'Qualificado pela IA', role: 'Fila de trabalho do time' },
  { id: '46939', name: 'Contato', role: 'Vendedor assumiu (bot nunca escreve aqui)' },
  { id: '46940', name: 'Qualificação', role: '—' },
  { id: '46941', name: 'Negociação', role: '—' },
  { id: '46942', name: 'Fechamento', role: '—' },
  { id: '46943', name: 'Declinado', role: 'Descarte (opt-out / número errado)' },
  { id: '54780', name: 'Fechado (ganho)', role: '—' },
]

export const customFieldsJundiai = [
  { field: 'tipo_plano', id: '6427' },
  { field: 'vidas', id: '3470' },
  { field: 'cidade', id: '3473' },
  { field: 'tem_plano_hoje', id: '6428' },
  { field: 'transcrição / resumo', id: '6431' },
  { field: 'qualifica_IA', id: '6432' },
  { field: 'motivo de perda', id: '8106' },
]

export const automationsJundiai = [
  {
    id: 'captacao',
    num: '1',
    name: 'Captação Jundiaí',
    short: 'Recebe a conversão da RD Station / LP e coloca o lead na coluna "Novo" (funil 7175).',
    workflowId: 'SHZ578B2JQgrY393',
    trigger: 'Webhook POST /webhook/rd-station-jundiai',
    flow: [
      { label: 'Webhook RD', desc: 'Porta de entrada que recebe o POST da RD Station a cada conversão de landing page (inclui aliases das LPs gndi-jundiai).' },
      { label: 'E0b/E1 Normalizar', desc: 'Lê nome/telefone/empresa, valida o telefone (DDD + 9) e infere cidade (Jundiaí) e tipo de plano empresarial quando há Empresa.' },
      { label: 'E2 Criar negociação', desc: 'Cria a negociação no funil 7175 na coluna "Novo" (46938), sem atribuir vendedor.' },
      { label: 'E4 Registrar no Supabase', desc: 'Insere a linha em chat_sessions (trigger_type=rdstation) para rastreio.' },
      { label: 'E5 Responder ao RD', desc: 'Devolve ao RD um resumo (recebidos, criados, ignorados). Sem telefone válido responde 200 ignorando.' },
    ],
    notes: [
      'Não atribui vendedor — a roleta só gira depois da qualificação.',
      'Normaliza telefone e trata os aliases das LPs *-jundiai.',
      'A roleta da unidade é a RPC proximo_vendedor(p_unidade="jundiai").',
    ],
  },
  {
    id: 'trilha',
    num: '2',
    name: '2 — Trilha Jundiaí',
    short: 'Orquestrador: aborda leads em "Novo", dispara a IA e cuida da transferência.',
    workflowId: 'g81aoz1RbkEtUof9',
    trigger: 'Cron 1 min + Cron 10 min + Webhook crm-transferir-jundiai',
    flow: [
      { label: 'Cron 1min → aborda "Novo"', desc: 'Busca negociações em "Novo" com travas anti-spam, anti-clone e LGPD (respeita opt-out).' },
      { label: 'C4 Monta contexto', desc: 'Reúne nome, cidade, plano e vidas e prepara a mensagem; resolve o WhatsApp conectado do agente em runtime (LON-23).' },
      { label: 'C6 Inicia agente IA', desc: 'Chama o agente 16306 (Agente SDR Jundiaí) para iniciar o atendimento no WhatsApp do lead.' },
      { label: 'C8 Move para IA atendendo', desc: 'Move o card para 73692 (IA atendendo) após o disparo aceito.' },
      { label: 'Cron 10min → transfere por silêncio', desc: 'Transfere quem não respondeu há ≥ 210 min, girando a roleta da unidade.' },
      { label: 'C9 Fallback de erro do agente', desc: 'Se o start falhar, entrega o lead em 73693 (Qualificado IA) já com consultor (motivo=erro_agente).' },
    ],
    notes: [
      'Ramo C (1min): aborda leads em Novo com travas anti-spam/anti-clone e LGPD.',
      'Ramo D (10min): transfere por silêncio quem não respondeu em 210 min.',
      'Ramo B: transferência manual/por motivo (compartilha nós do fluxo 3.A).',
    ],
  },
  {
    id: 'transferir',
    num: '3',
    name: '3.A — Transferir Jundiaí',
    short: 'Transfere o lead para consultor humano girando a roleta da unidade (proximo_vendedor).',
    workflowId: 'v4NwgIY2bwHRMzAC',
    trigger: 'Webhook POST /webhook/crm-transferir-jundiai',
    flow: [
      { label: 'Webhook', desc: 'Recebe a chamada do agente do CRM pedindo a transferência para um consultor humano.' },
      { label: 'B1 Validar', desc: 'Interpreta o motivo (qualificado, pediu_humano, tema_sensivel, opt_out etc.), limpa placeholders e normaliza telefone. Resolve o id_whatsapp do bot.' },
      { label: 'B1b Localizar negociação', desc: 'Busca no CRM os cards que existem agora pelo telefone, para não usar id antigo ("fantasma").' },
      { label: 'B2 Fila próximo vendedor', desc: 'Chama a RPC proximo_vendedor(p_unidade="jundiai") para girar a roleta e pegar o próximo consultor.' },
      { label: 'B4 Montar transferência', desc: 'Define o estágio de destino (Qualificado IA 73693 ou Declinado 46943), valida o card e monta o patch.' },
      { label: 'B3 Atribuir/mover', desc: 'Atualiza no CRM: id_usuario do vendedor, estágio e próxima ação.' },
      { label: 'B5/B6 Registrar e responder', desc: 'Grava no chat_sessions e informa ao agente para quem o lead foi transferido.' },
      { label: 'B7 Encerrar sessão', desc: 'Encerra a sessão do agente para ele não responder por cima do consultor.' },
    ],
    notes: [
      'Motivos: qualificado, pediu_humano, tema_sensivel, opt_out, numero_errado, sem_resposta.',
      'opt_out e numero_errado vão para "Declinado" sem gastar a roleta.',
      'Ferramentas do agente 16306 apontam para /crm-transferir-jundiai (não para a Bragança).',
    ],
  },
  {
    id: 'qualificado',
    num: '4',
    name: '3.B — Qualificado Jundiaí',
    short: 'Grava a qualificação do agente, calcula o score e encadeia a transferência.',
    workflowId: 'cg8qBn6xGJw7DJ1J',
    trigger: 'Webhook POST /webhook/crm-qualificacao-jundiai',
    flow: [
      { label: 'Webhook', desc: 'Recebe a qualificação enviada pelo agente ao encerrar a conversa (qualificado ou parcial).' },
      { label: 'A1 Validar / A1c Resolver id', desc: 'Normaliza os dados e localiza o card correto no CRM pelo id ou telefone.' },
      { label: 'A2/A3 Gravar', desc: 'Atualiza chat_sessions e a negociação no CRM com os dados da qualificação.' },
      { label: 'A4/A5 Campos', desc: 'Garante qualifica_IA = sim (6432) e grava os campos personalizados.' },
      { label: 'A5d Encadear transferência', desc: 'Encadeia automaticamente o webhook crm-transferir-jundiai (motivo qualificado).' },
    ],
    notes: [
      'qualifica_IA (6432) = sim é obrigatório para a trilha Qualifica IA.',
      'Encadeia a transferência automaticamente (uma ferramenta só).',
    ],
  },
  {
    id: 'qualifica-ia',
    num: '5',
    name: '4 — Qualifica IA Jundiaí',
    short: 'Move para "Qualificado pela IA" os leads já qualificados pelo bot.',
    workflowId: '3IzWVpOfHEl7DMPL',
    trigger: 'Cron a cada 1 min',
    flow: [
      { label: 'Listar / Filtrar', desc: 'Varre o funil 7175 e seleciona quem está em 73692 com qualifica_IA=sim (ou 73693 com dono bot).' },
      { label: 'Encadear transferência', desc: 'Encadeia crm-transferir-jundiai para girar a roleta e mover o card.' },
    ],
    notes: [
      'Verifica o campo qualifica_IA (6432) = sim.',
      'Card em 73693 com consultor humano é ignorado.',
      'Garante que o lead qualificado não fica preso na conversa com o bot.',
    ],
  },
  {
    id: 'handoff-130min',
    num: '6',
    name: 'Handoff 130min Jundiaí',
    short: 'Encaminha leads parados há 130 min em "IA atendendo" para a fila do time.',
    workflowId: 'Uzpqt0FHQMZIUqin',
    trigger: 'Cron a cada 5 min',
    flow: [
      { label: 'Listar Funil', desc: 'Pagina o funil 7175 (limit=200, teto de páginas) para encontrar candidatos.' },
      { label: 'Filtrar 130min IA', desc: 'Seleciona quem está há 130 min ou mais em 73692, com o tempo rastreado em staticData.' },
      { label: 'Fila próximo vendedor', desc: 'Gira a roleta (proximo_vendedor "jundiai") para pegar o consultor — a menos que o lead já tenha um vendedor humano.' },
      { label: 'CRM + Supabase', desc: 'Move o card para 73693, registra a transferência e encerra a sessão do agente.' },
    ],
    notes: [
      'Rastreia o tempo via staticData (não UpdatedAt).',
      'Respeita vendedor humano já atribuído — não gira a fila de novo.',
      'Não depende de WhatsApp conectado (não checa o agente).',
    ],
  },
  {
    id: 'monitor-leads',
    num: '7',
    name: 'Monitor leads parado Jundiaí',
    short: 'Detecta leads parados no funil 7175 e alerta o time de operação.',
    workflowId: 'atxSjHbxusO44HmU',
    trigger: 'Cron a cada 10 min',
    flow: [
      { label: 'Listar / Classificar', desc: 'Classifica leads parados (Novo ≥ 60 min, IA atendendo ≥ 150 min, Qualificado IA sem vendedor ≥ 45 min).' },
      { label: 'Alertar', desc: 'Publica no hub de alertas Long Life com unidade=jundiai.' },
    ],
    notes: [
      'Publica em /webhook/longlife-ops-alert com unidade=jundiai.',
      'Mesmo hub da Bragança (Alerta_Ops_LongLife).',
    ],
  },
]
